/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * KeyMech API
 * API documentation for KeyMech mechanical keyboard e-commerce platform
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export interface CreateProductDto { [key: string]: unknown }

export interface UpdateProductDto { [key: string]: unknown }

export interface CreateUserDto { [key: string]: unknown }

export interface UpdateUserDto { [key: string]: unknown }

export interface CreateCartDto { [key: string]: unknown }

export interface CreateCartItemDto { [key: string]: unknown }

export type appControllerGetHelloResponse200 = {
  data: void
  status: 200
}
    
export type appControllerGetHelloResponseSuccess = (appControllerGetHelloResponse200) & {
  headers: Headers;
};
;

export type appControllerGetHelloResponse = (appControllerGetHelloResponseSuccess)

export const getAppControllerGetHelloUrl = () => {


  

  return `/`
}

export const appControllerGetHello = async ( options?: RequestInit): Promise<appControllerGetHelloResponse> => {
  
  const res = await fetch(getAppControllerGetHelloUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: appControllerGetHelloResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as appControllerGetHelloResponse
}





export const getAppControllerGetHelloQueryKey = () => {
    return [
    `/`
    ] as const;
    }

    
export const getAppControllerGetHelloQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHello>>> = ({ signal }) => appControllerGetHello({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData> & { queryKey: QueryKey }
}

export type AppControllerGetHelloQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
export type AppControllerGetHelloQueryError = unknown



export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppControllerGetHelloQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create a new product
 */
export type productsControllerCreateResponse201 = {
  data: void
  status: 201
}

export type productsControllerCreateResponse400 = {
  data: void
  status: 400
}
    
export type productsControllerCreateResponseSuccess = (productsControllerCreateResponse201) & {
  headers: Headers;
};
export type productsControllerCreateResponseError = (productsControllerCreateResponse400) & {
  headers: Headers;
};

export type productsControllerCreateResponse = (productsControllerCreateResponseSuccess | productsControllerCreateResponseError)

export const getProductsControllerCreateUrl = () => {


  

  return `/products`
}

export const productsControllerCreate = async (createProductDto: CreateProductDto, options?: RequestInit): Promise<productsControllerCreateResponse> => {
  
  const res = await fetch(getProductsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createProductDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsControllerCreateResponse
}




export const getProductsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError,{data: CreateProductDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError,{data: CreateProductDto}, TContext> => {

const mutationKey = ['productsControllerCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productsControllerCreate>>, {data: CreateProductDto}> = (props) => {
          const {data} = props ?? {};

          return  productsControllerCreate(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof productsControllerCreate>>>
    export type ProductsControllerCreateMutationBody = CreateProductDto
    export type ProductsControllerCreateMutationError = void

    /**
 * @summary Create a new product
 */
export const useProductsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsControllerCreate>>, TError,{data: CreateProductDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof productsControllerCreate>>,
        TError,
        {data: CreateProductDto},
        TContext
      > => {

      const mutationOptions = getProductsControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all products
 */
export type productsControllerFindAllResponse200 = {
  data: void
  status: 200
}
    
export type productsControllerFindAllResponseSuccess = (productsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type productsControllerFindAllResponse = (productsControllerFindAllResponseSuccess)

export const getProductsControllerFindAllUrl = () => {


  

  return `/products`
}

export const productsControllerFindAll = async ( options?: RequestInit): Promise<productsControllerFindAllResponse> => {
  
  const res = await fetch(getProductsControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsControllerFindAllResponse
}





export const getProductsControllerFindAllQueryKey = () => {
    return [
    `/products`
    ] as const;
    }

    
export const getProductsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof productsControllerFindAll>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof productsControllerFindAll>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsControllerFindAll>>> = ({ signal }) => productsControllerFindAll({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type ProductsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof productsControllerFindAll>>>
export type ProductsControllerFindAllQueryError = unknown


/**
 * @summary Get all products
 */

export function useProductsControllerFindAll<TData = Awaited<ReturnType<typeof productsControllerFindAll>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof productsControllerFindAll>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getProductsControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get a product by ID
 */
export type productsControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type productsControllerFindOneResponse404 = {
  data: void
  status: 404
}
    
export type productsControllerFindOneResponseSuccess = (productsControllerFindOneResponse200) & {
  headers: Headers;
};
export type productsControllerFindOneResponseError = (productsControllerFindOneResponse404) & {
  headers: Headers;
};

export type productsControllerFindOneResponse = (productsControllerFindOneResponseSuccess | productsControllerFindOneResponseError)

export const getProductsControllerFindOneUrl = (id: string,) => {


  

  return `/products/${id}`
}

export const productsControllerFindOne = async (id: string, options?: RequestInit): Promise<productsControllerFindOneResponse> => {
  
  const res = await fetch(getProductsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productsControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsControllerFindOneResponse
}





export const getProductsControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/products/${id}`
    ] as const;
    }

    
export const getProductsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof productsControllerFindOne>>, TError = void>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof productsControllerFindOne>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProductsControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof productsControllerFindOne>>> = ({ signal }) => productsControllerFindOne(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof productsControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type ProductsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof productsControllerFindOne>>>
export type ProductsControllerFindOneQueryError = void


/**
 * @summary Get a product by ID
 */

export function useProductsControllerFindOne<TData = Awaited<ReturnType<typeof productsControllerFindOne>>, TError = void>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof productsControllerFindOne>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getProductsControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update a product
 */
export type productsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type productsControllerUpdateResponse400 = {
  data: void
  status: 400
}

export type productsControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type productsControllerUpdateResponseSuccess = (productsControllerUpdateResponse200) & {
  headers: Headers;
};
export type productsControllerUpdateResponseError = (productsControllerUpdateResponse400 | productsControllerUpdateResponse404) & {
  headers: Headers;
};

export type productsControllerUpdateResponse = (productsControllerUpdateResponseSuccess | productsControllerUpdateResponseError)

export const getProductsControllerUpdateUrl = (id: string,) => {


  

  return `/products/${id}`
}

export const productsControllerUpdate = async (id: string,
    updateProductDto: UpdateProductDto, options?: RequestInit): Promise<productsControllerUpdateResponse> => {
  
  const res = await fetch(getProductsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProductDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsControllerUpdateResponse
}




export const getProductsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError,{id: string;data: UpdateProductDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError,{id: string;data: UpdateProductDto}, TContext> => {

const mutationKey = ['productsControllerUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productsControllerUpdate>>, {id: string;data: UpdateProductDto}> = (props) => {
          const {id,data} = props ?? {};

          return  productsControllerUpdate(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof productsControllerUpdate>>>
    export type ProductsControllerUpdateMutationBody = UpdateProductDto
    export type ProductsControllerUpdateMutationError = void

    /**
 * @summary Update a product
 */
export const useProductsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsControllerUpdate>>, TError,{id: string;data: UpdateProductDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof productsControllerUpdate>>,
        TError,
        {id: string;data: UpdateProductDto},
        TContext
      > => {

      const mutationOptions = getProductsControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Delete a product
 */
export type productsControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type productsControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type productsControllerRemoveResponseSuccess = (productsControllerRemoveResponse200) & {
  headers: Headers;
};
export type productsControllerRemoveResponseError = (productsControllerRemoveResponse404) & {
  headers: Headers;
};

export type productsControllerRemoveResponse = (productsControllerRemoveResponseSuccess | productsControllerRemoveResponseError)

export const getProductsControllerRemoveUrl = (id: string,) => {


  

  return `/products/${id}`
}

export const productsControllerRemove = async (id: string, options?: RequestInit): Promise<productsControllerRemoveResponse> => {
  
  const res = await fetch(getProductsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: productsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as productsControllerRemoveResponse
}




export const getProductsControllerRemoveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['productsControllerRemove'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof productsControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  productsControllerRemove(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProductsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof productsControllerRemove>>>
    
    export type ProductsControllerRemoveMutationError = void

    /**
 * @summary Delete a product
 */
export const useProductsControllerRemove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof productsControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof productsControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getProductsControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create a new user
 */
export type usersControllerCreateResponse201 = {
  data: void
  status: 201
}
    
export type usersControllerCreateResponseSuccess = (usersControllerCreateResponse201) & {
  headers: Headers;
};
;

export type usersControllerCreateResponse = (usersControllerCreateResponseSuccess)

export const getUsersControllerCreateUrl = () => {


  

  return `/users`
}

export const usersControllerCreate = async (createUserDto: CreateUserDto, options?: RequestInit): Promise<usersControllerCreateResponse> => {
  
  const res = await fetch(getUsersControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUserDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerCreateResponse
}




export const getUsersControllerCreateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,{data: CreateUserDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,{data: CreateUserDto}, TContext> => {

const mutationKey = ['usersControllerCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerCreate>>, {data: CreateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  usersControllerCreate(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerCreate>>>
    export type UsersControllerCreateMutationBody = CreateUserDto
    export type UsersControllerCreateMutationError = unknown

    /**
 * @summary Create a new user
 */
export const useUsersControllerCreate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerCreate>>, TError,{data: CreateUserDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerCreate>>,
        TError,
        {data: CreateUserDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all users
 */
export type usersControllerFindAllResponse200 = {
  data: void
  status: 200
}
    
export type usersControllerFindAllResponseSuccess = (usersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type usersControllerFindAllResponse = (usersControllerFindAllResponseSuccess)

export const getUsersControllerFindAllUrl = () => {


  

  return `/users`
}

export const usersControllerFindAll = async ( options?: RequestInit): Promise<usersControllerFindAllResponse> => {
  
  const res = await fetch(getUsersControllerFindAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerFindAllResponse
}





export const getUsersControllerFindAllQueryKey = () => {
    return [
    `/users`
    ] as const;
    }

    
export const getUsersControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerFindAll>>, TError = unknown>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof usersControllerFindAll>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerFindAll>>> = ({ signal }) => usersControllerFindAll({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerFindAll>>>
export type UsersControllerFindAllQueryError = unknown


/**
 * @summary Get all users
 */

export function useUsersControllerFindAll<TData = Awaited<ReturnType<typeof usersControllerFindAll>>, TError = unknown>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof usersControllerFindAll>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get a user by ID
 */
export type usersControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type usersControllerFindOneResponse404 = {
  data: void
  status: 404
}
    
export type usersControllerFindOneResponseSuccess = (usersControllerFindOneResponse200) & {
  headers: Headers;
};
export type usersControllerFindOneResponseError = (usersControllerFindOneResponse404) & {
  headers: Headers;
};

export type usersControllerFindOneResponse = (usersControllerFindOneResponseSuccess | usersControllerFindOneResponseError)

export const getUsersControllerFindOneUrl = (id: string,) => {


  

  return `/users/${id}`
}

export const usersControllerFindOne = async (id: string, options?: RequestInit): Promise<usersControllerFindOneResponse> => {
  
  const res = await fetch(getUsersControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerFindOneResponse
}





export const getUsersControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/users/${id}`
    ] as const;
    }

    
export const getUsersControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof usersControllerFindOne>>, TError = void>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof usersControllerFindOne>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersControllerFindOne>>> = ({ signal }) => usersControllerFindOne(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type UsersControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof usersControllerFindOne>>>
export type UsersControllerFindOneQueryError = void


/**
 * @summary Get a user by ID
 */

export function useUsersControllerFindOne<TData = Awaited<ReturnType<typeof usersControllerFindOne>>, TError = void>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof usersControllerFindOne>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUsersControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





export type usersControllerUpdateResponse200 = {
  data: void
  status: 200
}
    
export type usersControllerUpdateResponseSuccess = (usersControllerUpdateResponse200) & {
  headers: Headers;
};
;

export type usersControllerUpdateResponse = (usersControllerUpdateResponseSuccess)

export const getUsersControllerUpdateUrl = (id: string,) => {


  

  return `/users/${id}`
}

export const usersControllerUpdate = async (id: string,
    updateUserDto: UpdateUserDto, options?: RequestInit): Promise<usersControllerUpdateResponse> => {
  
  const res = await fetch(getUsersControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerUpdateResponse
}




export const getUsersControllerUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdate>>, TError,{id: string;data: UpdateUserDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdate>>, TError,{id: string;data: UpdateUserDto}, TContext> => {

const mutationKey = ['usersControllerUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerUpdate>>, {id: string;data: UpdateUserDto}> = (props) => {
          const {id,data} = props ?? {};

          return  usersControllerUpdate(id,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerUpdate>>>
    export type UsersControllerUpdateMutationBody = UpdateUserDto
    export type UsersControllerUpdateMutationError = unknown

    export const useUsersControllerUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerUpdate>>, TError,{id: string;data: UpdateUserDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerUpdate>>,
        TError,
        {id: string;data: UpdateUserDto},
        TContext
      > => {

      const mutationOptions = getUsersControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
export type usersControllerRemoveResponse200 = {
  data: void
  status: 200
}
    
export type usersControllerRemoveResponseSuccess = (usersControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type usersControllerRemoveResponse = (usersControllerRemoveResponseSuccess)

export const getUsersControllerRemoveUrl = (id: string,) => {


  

  return `/users/${id}`
}

export const usersControllerRemove = async (id: string, options?: RequestInit): Promise<usersControllerRemoveResponse> => {
  
  const res = await fetch(getUsersControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: usersControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as usersControllerRemoveResponse
}




export const getUsersControllerRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerRemove'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerRemove(id,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerRemove>>>
    
    export type UsersControllerRemoveMutationError = unknown

    export const useUsersControllerRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getUsersControllerRemoveMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create a new cart
 */
export type cartControllerCreateResponse201 = {
  data: void
  status: 201
}

export type cartControllerCreateResponse400 = {
  data: void
  status: 400
}
    
export type cartControllerCreateResponseSuccess = (cartControllerCreateResponse201) & {
  headers: Headers;
};
export type cartControllerCreateResponseError = (cartControllerCreateResponse400) & {
  headers: Headers;
};

export type cartControllerCreateResponse = (cartControllerCreateResponseSuccess | cartControllerCreateResponseError)

export const getCartControllerCreateUrl = () => {


  

  return `/cart`
}

export const cartControllerCreate = async (createCartDto: CreateCartDto, options?: RequestInit): Promise<cartControllerCreateResponse> => {
  
  const res = await fetch(getCartControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCartDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: cartControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cartControllerCreateResponse
}




export const getCartControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerCreate>>, TError,{data: CreateCartDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof cartControllerCreate>>, TError,{data: CreateCartDto}, TContext> => {

const mutationKey = ['cartControllerCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cartControllerCreate>>, {data: CreateCartDto}> = (props) => {
          const {data} = props ?? {};

          return  cartControllerCreate(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CartControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof cartControllerCreate>>>
    export type CartControllerCreateMutationBody = CreateCartDto
    export type CartControllerCreateMutationError = void

    /**
 * @summary Create a new cart
 */
export const useCartControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerCreate>>, TError,{data: CreateCartDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cartControllerCreate>>,
        TError,
        {data: CreateCartDto},
        TContext
      > => {

      const mutationOptions = getCartControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Add an item to user cart
 */
export type cartControllerAddItemResponse201 = {
  data: void
  status: 201
}

export type cartControllerAddItemResponse400 = {
  data: void
  status: 400
}

export type cartControllerAddItemResponse404 = {
  data: void
  status: 404
}
    
export type cartControllerAddItemResponseSuccess = (cartControllerAddItemResponse201) & {
  headers: Headers;
};
export type cartControllerAddItemResponseError = (cartControllerAddItemResponse400 | cartControllerAddItemResponse404) & {
  headers: Headers;
};

export type cartControllerAddItemResponse = (cartControllerAddItemResponseSuccess | cartControllerAddItemResponseError)

export const getCartControllerAddItemUrl = (userId: string,) => {


  

  return `/cart/${userId}/items`
}

export const cartControllerAddItem = async (userId: string,
    createCartItemDto: CreateCartItemDto, options?: RequestInit): Promise<cartControllerAddItemResponse> => {
  
  const res = await fetch(getCartControllerAddItemUrl(userId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCartItemDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: cartControllerAddItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cartControllerAddItemResponse
}




export const getCartControllerAddItemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerAddItem>>, TError,{userId: string;data: CreateCartItemDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof cartControllerAddItem>>, TError,{userId: string;data: CreateCartItemDto}, TContext> => {

const mutationKey = ['cartControllerAddItem'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cartControllerAddItem>>, {userId: string;data: CreateCartItemDto}> = (props) => {
          const {userId,data} = props ?? {};

          return  cartControllerAddItem(userId,data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CartControllerAddItemMutationResult = NonNullable<Awaited<ReturnType<typeof cartControllerAddItem>>>
    export type CartControllerAddItemMutationBody = CreateCartItemDto
    export type CartControllerAddItemMutationError = void

    /**
 * @summary Add an item to user cart
 */
export const useCartControllerAddItem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerAddItem>>, TError,{userId: string;data: CreateCartItemDto}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cartControllerAddItem>>,
        TError,
        {userId: string;data: CreateCartItemDto},
        TContext
      > => {

      const mutationOptions = getCartControllerAddItemMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get cart for a user
 */
export type cartControllerGetCartResponse200 = {
  data: void
  status: 200
}

export type cartControllerGetCartResponse404 = {
  data: void
  status: 404
}
    
export type cartControllerGetCartResponseSuccess = (cartControllerGetCartResponse200) & {
  headers: Headers;
};
export type cartControllerGetCartResponseError = (cartControllerGetCartResponse404) & {
  headers: Headers;
};

export type cartControllerGetCartResponse = (cartControllerGetCartResponseSuccess | cartControllerGetCartResponseError)

export const getCartControllerGetCartUrl = (userId: string,) => {


  

  return `/cart/${userId}`
}

export const cartControllerGetCart = async (userId: string, options?: RequestInit): Promise<cartControllerGetCartResponse> => {
  
  const res = await fetch(getCartControllerGetCartUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: cartControllerGetCartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cartControllerGetCartResponse
}





export const getCartControllerGetCartQueryKey = (userId?: string,) => {
    return [
    `/cart/${userId}`
    ] as const;
    }

    
export const getCartControllerGetCartQueryOptions = <TData = Awaited<ReturnType<typeof cartControllerGetCart>>, TError = void>(userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof cartControllerGetCart>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCartControllerGetCartQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof cartControllerGetCart>>> = ({ signal }) => cartControllerGetCart(userId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof cartControllerGetCart>>, TError, TData> & { queryKey: QueryKey }
}

export type CartControllerGetCartQueryResult = NonNullable<Awaited<ReturnType<typeof cartControllerGetCart>>>
export type CartControllerGetCartQueryError = void


/**
 * @summary Get cart for a user
 */

export function useCartControllerGetCart<TData = Awaited<ReturnType<typeof cartControllerGetCart>>, TError = void>(
 userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof cartControllerGetCart>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getCartControllerGetCartQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Clear user cart
 */
export type cartControllerClearCartResponse200 = {
  data: void
  status: 200
}

export type cartControllerClearCartResponse404 = {
  data: void
  status: 404
}
    
export type cartControllerClearCartResponseSuccess = (cartControllerClearCartResponse200) & {
  headers: Headers;
};
export type cartControllerClearCartResponseError = (cartControllerClearCartResponse404) & {
  headers: Headers;
};

export type cartControllerClearCartResponse = (cartControllerClearCartResponseSuccess | cartControllerClearCartResponseError)

export const getCartControllerClearCartUrl = (userId: string,) => {


  

  return `/cart/${userId}`
}

export const cartControllerClearCart = async (userId: string, options?: RequestInit): Promise<cartControllerClearCartResponse> => {
  
  const res = await fetch(getCartControllerClearCartUrl(userId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: cartControllerClearCartResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cartControllerClearCartResponse
}




export const getCartControllerClearCartMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerClearCart>>, TError,{userId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof cartControllerClearCart>>, TError,{userId: string}, TContext> => {

const mutationKey = ['cartControllerClearCart'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cartControllerClearCart>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  cartControllerClearCart(userId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CartControllerClearCartMutationResult = NonNullable<Awaited<ReturnType<typeof cartControllerClearCart>>>
    
    export type CartControllerClearCartMutationError = void

    /**
 * @summary Clear user cart
 */
export const useCartControllerClearCart = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerClearCart>>, TError,{userId: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cartControllerClearCart>>,
        TError,
        {userId: string},
        TContext
      > => {

      const mutationOptions = getCartControllerClearCartMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Remove an item from cart
 */
export type cartControllerRemoveItemResponse200 = {
  data: void
  status: 200
}

export type cartControllerRemoveItemResponse404 = {
  data: void
  status: 404
}
    
export type cartControllerRemoveItemResponseSuccess = (cartControllerRemoveItemResponse200) & {
  headers: Headers;
};
export type cartControllerRemoveItemResponseError = (cartControllerRemoveItemResponse404) & {
  headers: Headers;
};

export type cartControllerRemoveItemResponse = (cartControllerRemoveItemResponseSuccess | cartControllerRemoveItemResponseError)

export const getCartControllerRemoveItemUrl = (cartItemId: string,) => {


  

  return `/cart/items/${cartItemId}`
}

export const cartControllerRemoveItem = async (cartItemId: string, options?: RequestInit): Promise<cartControllerRemoveItemResponse> => {
  
  const res = await fetch(getCartControllerRemoveItemUrl(cartItemId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: cartControllerRemoveItemResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cartControllerRemoveItemResponse
}




export const getCartControllerRemoveItemMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerRemoveItem>>, TError,{cartItemId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof cartControllerRemoveItem>>, TError,{cartItemId: string}, TContext> => {

const mutationKey = ['cartControllerRemoveItem'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cartControllerRemoveItem>>, {cartItemId: string}> = (props) => {
          const {cartItemId} = props ?? {};

          return  cartControllerRemoveItem(cartItemId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CartControllerRemoveItemMutationResult = NonNullable<Awaited<ReturnType<typeof cartControllerRemoveItem>>>
    
    export type CartControllerRemoveItemMutationError = void

    /**
 * @summary Remove an item from cart
 */
export const useCartControllerRemoveItem = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cartControllerRemoveItem>>, TError,{cartItemId: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof cartControllerRemoveItem>>,
        TError,
        {cartItemId: string},
        TContext
      > => {

      const mutationOptions = getCartControllerRemoveItemMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create a new order for a user
 */
export type ordersControllerCreateResponse201 = {
  data: void
  status: 201
}

export type ordersControllerCreateResponse404 = {
  data: void
  status: 404
}
    
export type ordersControllerCreateResponseSuccess = (ordersControllerCreateResponse201) & {
  headers: Headers;
};
export type ordersControllerCreateResponseError = (ordersControllerCreateResponse404) & {
  headers: Headers;
};

export type ordersControllerCreateResponse = (ordersControllerCreateResponseSuccess | ordersControllerCreateResponseError)

export const getOrdersControllerCreateUrl = (userId: string,) => {


  

  return `/orders/${userId}`
}

export const ordersControllerCreate = async (userId: string, options?: RequestInit): Promise<ordersControllerCreateResponse> => {
  
  const res = await fetch(getOrdersControllerCreateUrl(userId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ordersControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as ordersControllerCreateResponse
}




export const getOrdersControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ordersControllerCreate>>, TError,{userId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof ordersControllerCreate>>, TError,{userId: string}, TContext> => {

const mutationKey = ['ordersControllerCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ordersControllerCreate>>, {userId: string}> = (props) => {
          const {userId} = props ?? {};

          return  ordersControllerCreate(userId,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrdersControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof ordersControllerCreate>>>
    
    export type OrdersControllerCreateMutationError = void

    /**
 * @summary Create a new order for a user
 */
export const useOrdersControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ordersControllerCreate>>, TError,{userId: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof ordersControllerCreate>>,
        TError,
        {userId: string},
        TContext
      > => {

      const mutationOptions = getOrdersControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all orders for a user
 */
export type ordersControllerFindForUserResponse200 = {
  data: void
  status: 200
}

export type ordersControllerFindForUserResponse404 = {
  data: void
  status: 404
}
    
export type ordersControllerFindForUserResponseSuccess = (ordersControllerFindForUserResponse200) & {
  headers: Headers;
};
export type ordersControllerFindForUserResponseError = (ordersControllerFindForUserResponse404) & {
  headers: Headers;
};

export type ordersControllerFindForUserResponse = (ordersControllerFindForUserResponseSuccess | ordersControllerFindForUserResponseError)

export const getOrdersControllerFindForUserUrl = (userId: string,) => {


  

  return `/orders/user/${userId}`
}

export const ordersControllerFindForUser = async (userId: string, options?: RequestInit): Promise<ordersControllerFindForUserResponse> => {
  
  const res = await fetch(getOrdersControllerFindForUserUrl(userId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ordersControllerFindForUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as ordersControllerFindForUserResponse
}





export const getOrdersControllerFindForUserQueryKey = (userId?: string,) => {
    return [
    `/orders/user/${userId}`
    ] as const;
    }

    
export const getOrdersControllerFindForUserQueryOptions = <TData = Awaited<ReturnType<typeof ordersControllerFindForUser>>, TError = void>(userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ordersControllerFindForUser>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrdersControllerFindForUserQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ordersControllerFindForUser>>> = ({ signal }) => ordersControllerFindForUser(userId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ordersControllerFindForUser>>, TError, TData> & { queryKey: QueryKey }
}

export type OrdersControllerFindForUserQueryResult = NonNullable<Awaited<ReturnType<typeof ordersControllerFindForUser>>>
export type OrdersControllerFindForUserQueryError = void


/**
 * @summary Get all orders for a user
 */

export function useOrdersControllerFindForUser<TData = Awaited<ReturnType<typeof ordersControllerFindForUser>>, TError = void>(
 userId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ordersControllerFindForUser>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getOrdersControllerFindForUserQueryOptions(userId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get an order by ID
 */
export type ordersControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type ordersControllerFindOneResponse404 = {
  data: void
  status: 404
}
    
export type ordersControllerFindOneResponseSuccess = (ordersControllerFindOneResponse200) & {
  headers: Headers;
};
export type ordersControllerFindOneResponseError = (ordersControllerFindOneResponse404) & {
  headers: Headers;
};

export type ordersControllerFindOneResponse = (ordersControllerFindOneResponseSuccess | ordersControllerFindOneResponseError)

export const getOrdersControllerFindOneUrl = (id: string,) => {


  

  return `/orders/${id}`
}

export const ordersControllerFindOne = async (id: string, options?: RequestInit): Promise<ordersControllerFindOneResponse> => {
  
  const res = await fetch(getOrdersControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: ordersControllerFindOneResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as ordersControllerFindOneResponse
}





export const getOrdersControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/orders/${id}`
    ] as const;
    }

    
export const getOrdersControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof ordersControllerFindOne>>, TError = void>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ordersControllerFindOne>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrdersControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof ordersControllerFindOne>>> = ({ signal }) => ordersControllerFindOne(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ordersControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type OrdersControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof ordersControllerFindOne>>>
export type OrdersControllerFindOneQueryError = void


/**
 * @summary Get an order by ID
 */

export function useOrdersControllerFindOne<TData = Awaited<ReturnType<typeof ordersControllerFindOne>>, TError = void>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof ordersControllerFindOne>>, TError, TData>, fetch?: RequestInit}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getOrdersControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
