export const COLORWAYS = [
  {
    id: "dracula",
    name: "Dracula",
    style: "Dark Purple · Vivid Accents",
    vars: {
      "--key-base": "#282a36",
      "--key-legend": "#f8f8f2",
      "--key-mod": "#bd93f9",
      "--key-mod-legend": "#282a36",
      "--key-accent1": "#ff79c6",
      "--key-accent2": "#bd93f9",
      "--key-acc-legend": "#282a36",
      "--key-glow": "rgba(189, 147, 249, 0.45)",
      "--case-color": "#1e1f29",
      "--case-dark": "#191a22",
      "--case-darker": "#13141b",
      "--case-light": "#2e3044",
    },
    info: { base: "#282a36", legend: "#f8f8f2", accent: "#bd93f9" },
  },
  {
    id: "monokai",
    name: "Monokai",
    style: "Charcoal · Vivid Yellow",
    vars: {
      "--key-base": "#272822",
      "--key-legend": "#f8f8f2",
      "--key-mod": "#a6e22e",
      "--key-mod-legend": "#272822",
      "--key-accent1": "#e6db74",
      "--key-accent2": "#e6db74",
      "--key-acc-legend": "#272822",
      "--key-glow": "rgba(230, 219, 116, 0.45)",
      "--case-color": "#1e1f1a",
      "--case-dark": "#161712",
      "--case-darker": "#0e0f0a",
      "--case-light": "#33342e",
    },
    info: { base: "#272822", legend: "#f8f8f2", accent: "#a6e22e" },
  },
  {
    id: "slate-copper",
    name: "Slate Copper",
    style: "Charcoal · Burnished Copper",
    vars: {
      "--key-base": "#2e2e2e",
      "--key-legend": "#b87045",
      "--key-mod": "#b87045",
      "--key-mod-legend": "#f0d5c0",
      "--key-accent1": "#f0d5c0",
      "--key-accent2": "#f0d5c0",
      "--key-acc-legend": "#b87045",
      "--key-glow": "rgba(184, 112, 69, 0.4)",
      "--case-color": "#1e1e1e",
      "--case-dark": "#141414",
      "--case-darker": "#0a0a0a",
      "--case-light": "#2e2e2e",
    },
    info: { base: "#2e2e2e", legend: "#b87045", accent: "#b87045" },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    style: "Deep Indigo · Electric Blue",
    vars: {
      "--key-base": "#1a1b2e",
      "--key-legend": "#7aa2f7",
      "--key-mod": "#3d59a1",
      "--key-mod-legend": "#c0cff7",
      "--key-accent1": "#c0cff7",
      "--key-accent2": "#c0cff7",
      "--key-acc-legend": "#3d59a1",
      "--key-glow": "rgba(122, 162, 247, 0.45)",
      "--case-color": "#13141f",
      "--case-dark": "#0d0e18",
      "--case-darker": "#080910",
      "--case-light": "#24263d",
    },
    info: { base: "#1a1b2e", legend: "#7aa2f7", accent: "#3d59a1" },
  },
];

/**
 * Keycap atlases: MeshStandardMaterial.map samples TEXCOORD_0 (`uv`), but our PNG atlases are laid out
 * for TEXCOORD_1 (`uv2`) on keycap meshes—see `keycapGeometryForTexturedAtlas` in 3d-keyboard.
 * Set `atlasUsesUv2: false` only if a texture is authored for the first UV channel.
 */
export const KEYCAP_TEXTURES = [
  {
    id: "textured1",
    name: "Textured 1",
    path: "/t6.webp",
    knobColor: "red",
    caseColor: "#161616",
    atlasUsesUv2: true,
  },
  {
    id: "textured2",
    name: "Textured 2",
    path: "/t2.webp",
    knobColor: "#00FFFF",
    caseColor: "#1D1D54",
    atlasUsesUv2: true,
  },
  {
    id: "textured3",
    name: "Textured 3",
    path: "/t3.webp",
    knobColor: "#9FE2BF",
    caseColor: "#13251E",
    atlasUsesUv2: true,
  },
] as const;

export const ROWS = [
  [
    ["Esc", "base"],
    ["!\n1", "base"],
    ["@\n2", "base"],
    ["#\n3", "base"],
    ["$\n4", "base"],
    ["%\n5", "base"],
    ["^\n6", "base"],
    ["&\n7", "base"],
    ["*\n8", "base"],
    ["(\n9", "base"],
    [")\n0", "base"],
    ["_\n-", "base"],
    ["+\n=", "base"],
    ["Backspace", "mod", "w200"],
    ["~\n`", "mod"],
  ],
  [
    ["Tab", "mod", "w150"],
    ["Q", "base"],
    ["W", "base"],
    ["E", "base"],
    ["R", "base"],
    ["T", "base"],
    ["Y", "base"],
    ["U", "base"],
    ["I", "base"],
    ["O", "base"],
    ["P", "base"],
    ["{\n[", "base"],
    ["}\n]", "base"],
    ["|\n\\", "base", "w150"],
    ["Del", "mod"],
  ],
  [
    ["CapsLock", "mod", "w175"],
    ["A", "base"],
    ["S", "base"],
    ["D", "base"],
    ["F", "base"],
    ["G", "base"],
    ["H", "base"],
    ["J", "base"],
    ["K", "base"],
    ["L", "base"],
    [":\n;", "base"],
    ["\"\n'", "base"],
    ["Enter", "acc1", "w225"],
    ["PgUp", "mod"],
  ],
  [
    ["Shift", "mod", "w225"],
    ["Z", "base"],
    ["X", "base"],
    ["C", "base"],
    ["V", "base"],
    ["B", "base"],
    ["N", "base"],
    ["M", "base"],
    ["<\n,", "base"],
    [">\n.", "base"],
    ["?\n/", "base"],
    ["Shift", "mod", "w175"],
    ["↑", "acc1"],
    ["PgDn", "mod"],
  ],
  [
    ["Ctrl", "mod", "w125"],
    ["Win", "mod", "w125"],
    ["Alt", "mod", "w125"],
    ["", "acc1", "w625"],
    ["Alt", "mod"],
    ["Fn", "mod"],
    ["Ctrl", "mod"],
    ["←", "acc1"],
    ["↓", "acc1"],
    ["→", "acc1"],
  ],
];
